CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE CONTEST_STATUS AS ENUM('Scheduled', 'Active', 'Closed');

CREATE TABLE CONTESTS (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    start_date BIGINT NOT NULL,
    end_date BIGINT NOT NULL,
    status CONTEST_STATUS NOT NULL,
    owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())
)